// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	initPanel: () => __TAURI_INVOKE<void>("init_panel"),
	hidePanel: () => __TAURI_INVOKE<void>("hide_panel"),
	togglePanelAtTrayRect: (rect: TrayRectInput) => __TAURI_INVOKE<void>("toggle_panel_at_tray_rect", { rect }),
	openDevtools: () => __TAURI_INVOKE<void>("open_devtools"),
	setLogLevel: (level: string) => typedError<null, string>(__TAURI_INVOKE("set_log_level", { level })),
	copyLogPath: () => typedError<null, string>(__TAURI_INVOKE("copy_log_path")),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	startProbeBatch: (batchId: string | null, pluginIds: string[] | null) => typedError<ProbeBatchStarted, string>(__TAURI_INVOKE("start_probe_batch", { batchId, pluginIds })),
	listPlugins: () => __TAURI_INVOKE<PluginMeta[]>("list_plugins"),
	getLogPath: () => typedError<string, string>(__TAURI_INVOKE("get_log_path")),
	/**
	 *  Return the currently enabled, cached usage snapshots so the frontend can
	 *  hydrate immediately on open (or after the WebView was throttled while
	 *  hidden) without waiting for a fresh probe.
	 */
	getCachedUsage: () => __TAURI_INVOKE<CachedPluginSnapshot[]>("get_cached_usage"),
	/**
	 *  Unix-ms timestamp of the next scheduled auto-update, or `None` if the
	 *  scheduler hasn't set it yet. Lets the UI countdown track the real native
	 *  schedule instead of resetting on every panel open.
	 */
	getNextUpdateAt: () => __TAURI_INVOKE<number | null>("get_next_update_at"),
	/**
	 *  Update the global shortcut registration.
	 *  Pass `null` to disable the shortcut, or a shortcut string like "CommandOrControl+Shift+U".
	 */
	updateGlobalShortcut: (shortcut: string | null) => typedError<null, string>(__TAURI_INVOKE("update_global_shortcut", { shortcut })),
	/**
	 *  Open the macOS System Settings → Notifications pane. The opener plugin doesn't handle the
	 *  `x-apple.systempreferences:` scheme, so shell out to `open`, which does.
	 */
	openNotificationSettings: () => typedError<null, string>(__TAURI_INVOKE("open_notification_settings")),
	sendPaceNotification: (title: string, body: string) => typedError<null, string>(__TAURI_INVOKE("send_pace_notification", { title, body })),
	checkBetaUpdate: () => typedError<{
	version: string,
} | null, string>(__TAURI_INVOKE("check_beta_update")),
	downloadBetaUpdate: () => typedError<null, string>(__TAURI_INVOKE("download_beta_update")),
	installBetaUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_beta_update")),
	clinepassKeyStatus: () => __TAURI_INVOKE<ClinePassKeyStatus>("clinepass_key_status"),
	saveClinepassKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("save_clinepass_key", { key })),
	clearClinepassKey: () => typedError<null, string>(__TAURI_INVOKE("clear_clinepass_key")),
	openrouterKeyStatus: () => __TAURI_INVOKE<KeyStatus>("openrouter_key_status"),
	saveOpenrouterKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("save_openrouter_key", { key })),
	clearOpenrouterKey: () => typedError<null, string>(__TAURI_INVOKE("clear_openrouter_key")),
};

/** Events */
export const events = {
	betaUpdateProgress: makeEvent<BetaUpdateProgress>("beta-update:progress"),
	probeBatchComplete: makeEvent<ProbeBatchComplete>("probe:batch-complete"),
	probeResult: makeEvent<ProbeResult>("probe:result"),
};

/* Types */
export type BarChartPoint = {
	label: string,
	value: number | null,
	valueLabel: string | null,
};

export type BetaUpdateInfo = {
	version: string,
};

export type BetaUpdateProgress = { event: "Started"; data: {
	content_length: number | null,
} } | { event: "Progress"; data: {
	chunk_length: number | null,
} } | { event: "Finished" };

export type CachedPluginSnapshot = {
	providerId: string,
	displayName: string,
	plan: string | null,
	lines: MetricLine[],
	fetchedAt: string,
};

export type ClinePassKeyStatus = {
	saved: boolean,
	fromEnv: boolean,
};

/**  Which sources currently hold a key — drives the API Keys card state without exposing the key. */
export type KeyStatus = {
	/**  A key is saved in a config file. */
	saved: boolean,
	/**  A key is present in the environment (a saved key takes precedence — the plugin checks files first). */
	fromEnv: boolean,
};

export type ManifestLineDto = {
	type: string,
	label: string,
	scope: string,
	escalateAtPercent: number | null,
};

export type MetricLine = { type: "text"; label: string; value: string; color: string | null; subtitle: string | null; resetExpiry: string[] | null } | { type: "progress"; label: string; used: number | null; limit: number | null; format: ProgressFormat; resetsAt: string | null; periodDurationMs: number | null; color: string | null } | { type: "badge"; label: string; text: string; color: string | null; subtitle: string | null } | { type: "barChart"; label: string; points: BarChartPoint[]; note: string | null; color: string | null };

export type PluginLinkDto = {
	label: string,
	url: string,
};

export type PluginMeta = {
	id: string,
	name: string,
	iconUrl: string,
	brandColor: string | null,
	lines: ManifestLineDto[],
	links: PluginLinkDto[],
	/**
	 *  Ordered list of primary metric candidates (sorted by primaryOrder).
	 *  Frontend picks the first one that exists in runtime data.
	 */
	primaryCandidates: string[],
	/**
	 *  Label of the progress line marked `"period": "weekly"`, if any.
	 *  Drives the menubar weekly-metric preference.
	 */
	weeklyCandidate: string | null,
	/**  Optional pair of progress-line labels for Multi menubar style. */
	multiTrayLines: string[],
	/**  Optional progress-line label for single-provider menubar styles. */
	trayPrimaryLabel: string | null,
	/**
	 *  Whether the provider's credentials/config were found on this machine.
	 *  New users get detected plugins enabled by default; undetected ones start
	 *  disabled so they don't show error cards for providers they don't use.
	 */
	detected: boolean,
};

export type PluginOutput = {
	providerId: string,
	displayName: string,
	plan: string | null,
	lines: MetricLine[],
	iconUrl: string,
};

export type ProbeBatchComplete = {
	batchId: string,
};

export type ProbeBatchStarted = {
	batchId: string,
	pluginIds: string[],
};

export type ProbeResult = {
	batchId: string,
	output: PluginOutput,
};

export type ProgressFormat = { kind: "percent" } | { kind: "dollars" } | { kind: "count"; suffix: string };

export type TrayRectInput = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

